######################################################################
# Automatically generated by qmake (3.0) Tue Nov 18 15:07:10 2014
######################################################################

CONFIG -= app_bundle
QT += network
TEMPLATE = app
TARGET = tuio2qt
INCLUDEPATH += .

# Input
SOURCES += \
    main.cpp \
    qoscbundle.cpp \
    qoscmessage.cpp

HEADERS += \
    qoscbundle_p.h \
    qoscmessage_p.h
